### ISSUE TITLE
Getting FileInfo instances from the VisIt-SWT classes

### ISSUE THREAD

**Issue by jdeyton** [visit-vis/visit_java_client#11]
When trying to use the `VisItSwtWidget` to render mesh files over the network, I've come across a problem in accessing VisIt's information about the mesh file.

Currently, `FileInfo` instances contain all of the information I could want to find out what type of plots can be rendered from a particular mesh file.

The problem is that I cannot (at least I haven't figured out how to) obtain a `FileInfo` without going through a `VisItSwtWidget`. Doing so is an issue because I need to dedicate UI resources to construct a `VisItSwtWidget` (as an SWT `Canvas` sub-class, it needs a parent `Composite`). Ideally, the `VisItSwtConnection` class or its `ViewerMethods` could expose the `FileInfo` getter... after all, I have to call `ViewerMethods#openDatabase(filename:String)` to let VisIt know about the file I want to open.

I can think of a few uses for this, but the primary goal in my case is to get information about what's in a file before actually opening up a VisIt window.

My current workaround (which is nasty) is to create a hidden shell, then create a `VisItSwtWidget`, get the `FileInfo`, then dispose the shell. This causes some nasty exceptions in the background (I can't remember if it throws a widget disposed exception or a null pointer exception).

Here's the workaround code:

~~~~
		FileInfo info = null;

		// To get the FileInfo from VisIt, you have to open the file path in the
		// VisIt database first, then request a FileInfo object from the
		// connection.

		if (canvas != null) {
			canvas.getViewerMethods().openDatabase(sourcePath);
			info = canvas.getFileInfo();
		} else {
			// If there is no Canvas available yet, create a temporary one.
			Shell tmpShell = new Shell(Display.getCurrent());
			VisItSwtWidget tmpCanvas = (canvas != null ? canvas : createCanvas(
					tmpShell, SWT.NONE));
			tmpCanvas.getViewerMethods().openDatabase(sourcePath);
			info = tmpCanvas.getFileInfo();
			tmpShell.dispose();
		}

		return info;
~~~~

Thanks!
Jordan

**Comment by HarinarayanKrishnan** [comment]
Thanks for letting me know. I will move the FileInfo class to be constructed within ViewerMethods so that one can access the contents directly without having to create a swt widget.

**Comment by jdeyton** [comment]
Not a problem! Thanks for taking a look at it!

**Comment by HarinarayanKrishnan** [comment]
Hi Jordan,

I pushed a change to expose the FileInfo class from ViewerMethods. Now you
can call OpenDatabase() then use getDatabaseInfo() to retrieve the contents
of the dataset.

Best regards,
Hari

**Comment by jdeyton** [comment]
That works great! Thanks!

The master branch in our repo should now be using the new method you added instead of the previous `VisItSwtWidget.getFileInfo()`. I've also updated the branch I'm working on, so as far as I can tell there's nothing else using the method on `VisItSwtWidget`. I guess you can remove it whenever you want.

Feel free to close this ticket, too.

Thanks again,
Jordan
